---
- name: Filter unique staks
  ansible.builtin.set_fact:
    container_stacks: "{{ containers | map(attribute='stack') | unique }}"

- name: Ensure destination for compose file exists
  ansible.builtin.file:
    path: "{{ docker_compose_generator_output_path }}/{{ item }}"
    state: directory
  loop: "{{ container_stacks }}"
    
- name: Write docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_generator_output_path }}/{{ container_stacks }}/docker-compose.yml"
    owner: "{{ docker_compose_generator_uid }}"
    group: "{{ docker_compose_generator_gid }}"
  loop: "{{ container_stacks }}"
  loop_control:
    loop_var: loop_stack
  vars:
    stack_containers: "{{ containers | selectattr('stack', '==', loop_stack) }}"
